### ISSUE TITLE
Update contribute page

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#156]
Add notes on:
- [x] Git and GitHub:
  - [x] Issue labels (categories, see #155)
  - [x] Link to issues labelled 'good first issue'
  - [x] Link to bug page
  - [x] Link to upcoming releases (GitHub milestones, sorted alphabetically)
  - [x] PR titles (#137)
  - [x] Release flow (`setuptools-scm`, see #114)
  - [x] Issue dependency management with ZenHub
  - [x] Milestones and how they relate to releases and ZenHub
- [x] Continuous integration with GitHub Actions (#150)
- [x] Replace [section on Python conventions](https://pwa.readthedocs.io/projects/expertsystem/en/0.2.0-alpha/contribute.html#python-conventions) with a section about linters.
